language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
matrix:
  include:
    - python: 2.6
      env: TEST=slow
    - python: 2.7
      env: TEST=slow
    - python: 3.2
      env: TEST=slow
    - python: 3.3
      env: TEST=slow
install: >
  pip install -r requirements-dev.txt --use-mirrors &&
  sudo apt-get install redis-server &&
  sudo service redis-server start
script: >
  ./tests/travis/run.sh
